/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frms;
import maderera.FrmPrincipal;
/**
 *
 * @author user}
 */
public class Fmr_AAPRIN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fmr_AAPRIN.class.getName());

    /**
     * Creates new form Fmr_AAPRIN
     */
    public Fmr_AAPRIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        INGRESAR = new javax.swing.JButton();
        INGRESAR1 = new javax.swing.JButton();
        INGRESAR2 = new javax.swing.JButton();
        INGRESAR3 = new javax.swing.JButton();
        INGRESAR4 = new javax.swing.JButton();
        INGRESAR5 = new javax.swing.JButton();
        INGRESAR6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SERVICIOS");

        INGRESAR.setText("INGRESAR");
        INGRESAR.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        INGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESARActionPerformed(evt);
            }
        });

        INGRESAR1.setText("INGRESAR");
        INGRESAR1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));
        INGRESAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR1ActionPerformed(evt);
            }
        });

        INGRESAR2.setText("INGRESAR");
        INGRESAR2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        INGRESAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR2ActionPerformed(evt);
            }
        });

        INGRESAR3.setText("INGRESAR");
        INGRESAR3.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        INGRESAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR3ActionPerformed(evt);
            }
        });

        INGRESAR4.setText("INGRESAR");
        INGRESAR4.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Clientes"));
        INGRESAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR4ActionPerformed(evt);
            }
        });

        INGRESAR5.setText("INGRESAR");
        INGRESAR5.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));
        INGRESAR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR5ActionPerformed(evt);
            }
        });

        INGRESAR6.setText("INGRESAR");
        INGRESAR6.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Productos"));
        INGRESAR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(INGRESAR2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(INGRESAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(INGRESAR1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(INGRESAR5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addComponent(INGRESAR6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(INGRESAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(INGRESAR4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INGRESAR)
                    .addComponent(INGRESAR3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INGRESAR1)
                    .addComponent(INGRESAR5))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INGRESAR2)
                    .addComponent(INGRESAR6)
                    .addComponent(INGRESAR4))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESARActionPerformed
        // TODO add your handling code here:
        FrmCliente a = new FrmCliente();
        a.show();
    }//GEN-LAST:event_INGRESARActionPerformed

    private void INGRESAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESAR1ActionPerformed
        // TODO add your handling code here:
        FrmEmpleado a = new FrmEmpleado();
        a.show();
    }//GEN-LAST:event_INGRESAR1ActionPerformed

    private void INGRESAR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESAR6ActionPerformed
        // TODO add your handling code here:
        FrmListaProductos a = new FrmListaProductos();
        a.show();
    }//GEN-LAST:event_INGRESAR6ActionPerformed

    private void INGRESAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESAR3ActionPerformed
        // TODO add your handling code here:
        FrmLogin a = new FrmLogin();
        a.show();
    }//GEN-LAST:event_INGRESAR3ActionPerformed

    private void INGRESAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESAR2ActionPerformed
        // TODO add your handling code here:
        FrmProducto a = new FrmProducto();
        a.show();
    }//GEN-LAST:event_INGRESAR2ActionPerformed

    private void INGRESAR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESAR5ActionPerformed
        // TODO add your handling code here:
        FrmProveedor a = new FrmProveedor();
        a.show();   
    }//GEN-LAST:event_INGRESAR5ActionPerformed

    private void INGRESAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESAR4ActionPerformed
        // TODO add your handling code here:
        FrmPrincipal a = new FrmPrincipal();
        a.show();
    }//GEN-LAST:event_INGRESAR4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fmr_AAPRIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INGRESAR;
    private javax.swing.JButton INGRESAR1;
    private javax.swing.JButton INGRESAR2;
    private javax.swing.JButton INGRESAR3;
    private javax.swing.JButton INGRESAR4;
    private javax.swing.JButton INGRESAR5;
    private javax.swing.JButton INGRESAR6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
